### ISSUE TITLE
The specific json file cannot get from official tvm

### ISSUE THREAD

**Issue by juinshell** [SJTU-IPADS/reef#3]
Hello! I was reading your paper and it says that the system works on CUDA as well. Have you done any experiments about CUDA with tvm? I applied tvm_generate_model.py from ~/script to three versions of tvm from 0.7.0-0.9.0 and it did not work. I can't get the 2 json files as you show--raw_schedule_file.json & graph_json.json.Other than that, how did you get the .cu file? 

https://github.com/SJTU-IPADS/reef/blob/0a25de5d60edaef524752a921a8c72e131137879/script/tvm_generate_model.py#L59-L63

Both operations here are more or less buggy in the official tvm v0.7.0-0.9.0.

I would be very grateful if you could solve my problem!

**Comment by francis0407** [comment]
1. These two json files can only be generated by a customized version TVM, please see https://github.com/SJTU-IPADS/reef/issues/1 and https://github.com/francis0407/tvm/tree/reef.

2. The original `.cu` file can be dumped by something like `lib.imported_modules[0].get_source()`. The transformation can be done by two scripts, see https://github.com/SJTU-IPADS/reef/blob/0a25de5d60edaef524752a921a8c72e131137879/resource/Makefile#L40.

3. This artifact does not support NVIDIA GPU (CUDA). We're currently refactoring the code base to support CUDA.

**Comment by juinshell** [comment]
Thanks a million for answering me!
Now I can generate `.json` file and `.cu` file(which just includes GPU kernels) by your code!
However, when I want to launch kernels from resnet18 and get the correct output, I imitate your workflow in your test folder and `executor_base.cpp`, found that the key I parsed from `.params` 
https://github.com/SJTU-IPADS/reef/blob/0a25de5d60edaef524752a921a8c72e131137879/src/reef/executor/model.cpp#L118
cannot match the name from storage
https://github.com/SJTU-IPADS/reef/blob/0a25de5d60edaef524752a921a8c72e131137879/src/reef/executor/executor_base.cpp#L85-L89
The key from `.params` includes `bn_data_gamma`, `bn0_moving_mean`,`stage1_unit1_bn1_moving_var` ... , but the name from `.json` storage looks like `null`, `data`, `p10`, `p20`. So I cannot load param from file correctly.
Looking forward to your further reply!

**Comment by francis0407** [comment]
How did you get the `.params` file?

**Comment by juinshell** [comment]
```python
from tvm import relay
...
param_file = open(sys.argv[4], "w+b")  # params
batch_size = 1
num_class = 1000
image_shape = (3, 224, 224)
data_shape = (batch_size,) + image_shape
out_shape = (batch_size, num_class)

mod, params = relay.testing.resnet.get_workload(
    num_layers=18, batch_size=batch_size, image_shape=image_shape
)
...
def dump_params(params, f):
    import array
    magic = bytes("TVM_MODEL_PARAMS\0", "ascii")
    f.write(magic)
    f.write(array.array('Q',[len(params)]).tobytes())
    for k in params.keys():
        print(k)
        param = array.array('f', params[k].asnumpy().flatten().tolist())
        f.write(bytes(k, "ascii"))
        f.write(bytes("\0", "ascii"))
        f.write(array.array('Q',[len(param)]).tobytes())
        f.write(param.tobytes())

dump_params(params, param_file)
param_file.close()
```

**Comment by francis0407** [comment]
Try this
```Python
mod, params = relay.testing.resnet.get_workload(
    num_layers=18, batch_size=batch_size, image_shape=image_shape
)
print(params.keys())
...

with tvm.transform.PassContext(opt_level=opt_level):
    graph_json, lib, params = relay.build(mod, target, params=params)
print(params.keys())
```

The second `params` might be the one with names like "p10, p20".

**Comment by juinshell** [comment]
Oh! I have got the right `.param` and output by using your method!
Thanks again for your timely assistance!
