### ISSUE TITLE
对hipResetWavefronts有点迷糊

### ISSUE THREAD

**Issue by lovelydett** [SJTU-IPADS/reef#8]
请问up主 hipResetWavefronts 的具体作用是啥？ 是让CU停下来吗，这个动作是CPU做的吗？如果在NVIDIA GPU上有类似的函数吗，求详解！谢谢！

**Comment by francis0407** [comment]
`hipResetWavefronts` is used to kill the GPU kernels that are currently running on CUs.

This is a new API we introduced in this work, the implementation is [here (user-space driver)](https://github.com/SJTU-IPADS/reef-artifacts/blob/8750974f2d6655525a2cc317bf2471914fe68dab/reef-env/hip/rocclr/hip_stream.cpp#L644) and [here (kernel-space driver)](https://github.com/SJTU-IPADS/reef-artifacts/blob/8750974f2d6655525a2cc317bf2471914fe68dab/reef-env/amdgpu-dkms/amdgpu-4.3-52/amd/amdkfd/kfd_chardev.c#L3162).

**Comment by lovelydett** [comment]
> `hipResetWavefronts` is used to kill the GPU kernels that are currently running on CUs.
> 
> This is a new API we introduced in this work, the implementation is [here (user-space driver)](https://github.com/SJTU-IPADS/reef-artifacts/blob/8750974f2d6655525a2cc317bf2471914fe68dab/reef-env/hip/rocclr/hip_stream.cpp#L644) and [here (kernel-space driver)](https://github.com/SJTU-IPADS/reef-artifacts/blob/8750974f2d6655525a2cc317bf2471914fe68dab/reef-env/amdgpu-dkms/amdgpu-4.3-52/amd/amdkfd/kfd_chardev.c#L3162).

Thanks for reply! So, to my understanding, you modify (add) a new function in the driver for a AMD GPU to implement the preempt semantic, is that right? 0.0 

If you dont mind, I have one more question about the semantic of "reset" in `dbgdev_wave_reset_wavefronts`.  Is the concept of **wave front** similar to the concept of **warp** of Nvidia GPU? and how does it stop the running kernel (maybe across multiple wave fronts?) by reseting them to the starting point of the running kernel? 

Looking forward to your reply!

**Comment by francis0407** [comment]
> Thanks for reply! So, to my understanding, you modify (add) a new function in the driver for a AMD GPU to implement the preempt semantic, is that right? 0.0

That's right.
 
> Is the concept of **wave front** similar to the concept of **warp** of Nvidia GPU? 

Yes.

> and how does it stop the running kernel (maybe across multiple wave fronts?) by reseting them to the starting point of the running kernel?

As far as I know, `dbgdev_wave_reset_wavefronts` stops the running kernel, and resets the execution state of the CU (e.g., registers).  The killed kernel will not  be executed again.

**Comment by lovelydett** [comment]
> > Thanks for reply! So, to my understanding, you modify (add) a new function in the driver for a AMD GPU to implement the preempt semantic, is that right? 0.0
> 
> That's right.
>  
> > Is the concept of **wave front** similar to the concept of **warp** of Nvidia GPU? 
> 
> Yes.
> 
> > and how does it stop the running kernel (maybe across multiple wave fronts?) by reseting them to the starting point of the running kernel?
> 
> As far as I know, `dbgdev_wave_reset_wavefronts` stops the running kernel, and resets the execution state of the CU (e.g., registers).  The killed kernel will not  be executed again.

Thanks for your reply！
